
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-11T09:41:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "57ec4c4f65f9bd324872aea0cfe3e04ba84e9e91",
 "version": "1.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
