#FreeMind 1.0.1
#Thu Mar 12 05:40:30 EDT 2020
lastOpened=MindMap\:/Users/sean/Desktop/Kajabi Projects.mm;MindMap\:/Users/sean/Dropbox/maps/freemind/bodytalk.mm;MindMap\:/Users/sean/Desktop/Ten Pips.mm;
appwindow_y=23
appwindow_state=0
appwindow_height=777
appwindow_width=1276
appwindow_x=0
toolbarVisible=true
load_new_map_when_no_other_is_specified=false
mindmap_last_state_map_storage=<?xml version\="1.0" encoding\="UTF-8"?><mindmap_last_state_map_storage last_focused_tab\="-1"><mindmap_last_state_storage last_changed\="1448811198366" tab_index\="-1" restorable_name\="MindMap\:/Users/sean/Desktop/Kajabi Projects.mm" last_zoom\="1.0" x\="949" y\="406" last_selected\="ID_1074580863"><node_list_member node\="ID_1074580863"/></mindmap_last_state_storage></mindmap_last_state_map_storage>
leftToolbarVisible=true
antialiasEdges=true
split_pane_last_position=0
split_pane_position=-1
antialiasAll=false
onStartIfNotSpecified=
